### ISSUE TITLE
[suggestion] Have all audio go both ways 

### ISSUE THREAD

**Issue by DerpedCrusader** [n33kos/AlwaysHearActiveWalkie#1] opened 2023-11-29 23:46 UTC
Have it so the radios pick up all the audio around it

So say, 

Player 1 holds the radio and activates it, player 2 can talk into it, and it'll pick up their voice (along with all other ambient sounds)

**Comment by wasniahC** [comment] 2023-12-09 17:57
+1 to this. the game already works like this to some extent, vanilla functionality letting you hear things like boombox music or record player in background when someone's talking - just not other players around them.

**Comment by n33kos** [comment] 2024-01-05 02:31
Hmmm, I'll try to reproduce this issue as I think it may be a bug, The way its written it _should_ already be picking up the nearby objects and players. Maybe I overlooked or misunderstood something.

Thanks for the submission!

**Comment by n33kos** [comment] 2024-01-06 00:43
I'm unable to reproduce this issue, I was able to hear ambient sounds coming through a walkie talkie not held by the active player. I believe this bug was corrected in version 1.4.3. Closing this issue

**Closed as completed by n33kos** 2024-01-06 00:43 UTC
