### ISSUE TITLE
Can't Interact with E while holding Walkie-Talkie

### ISSUE THREAD

**Issue by ElvesLie** [n33kos/AlwaysHearActiveWalkie#8] opened 2024-01-05 07:26 UTC
I, the host can, but the other players can't. I'm wondering if this is possibly an issue with the mod itself or conflicting with other mods?

**Comment by n33kos** [comment] 2024-01-06 01:05
@ElvesLie This mod doesn't touch any of the input code, I've not been able to reproduce this issue.

One of the friends I play with said the same thing happened to them but I believe it was caused by some other combination of mods. Its possible there is some subtle interaction between the `___holdingWalkieTalkie` and some input logic in the vanilla game, but nobody else I was playing with had the same issues.

I'm going to close this issue. If you can provide reliable reproduction steps, please open up a new issue and I can look into it. Unfortunately if I can't reproduce it I won't be able to come up with a fix.

**Closed as completed by n33kos** 2024-01-06 01:05 UTC
